### ISSUE TITLE
binder and ashmem kernel modules missing

### ISSUE THREAD

**Issue by Fornball** [cb-linux/breath#106]
I am running ubuntu 21.10 of a usb on my chromebook and Im trying to get [Anbox](https://anbox.io/) working. For anbox to work, the binder and ashmem kernel modules need to be installed, which they are supposed to be, starting from ubuntu 19.04. 
[Manually installing](https://docs.anbox.io/userguide/install_kernel_modules.html) doesnt work as the ppa doesnt support newer ubuntu versions

**Comment by MilkyDeveloper** [comment]
Fixed in latest kernel build, run `bash updatekernel.sh` on the host PC or `updatekernel-on-emmc` on your chromebook.

**Comment by Fornball** [comment]
After running update-on-emmc on the chromebook: 
![Screenshot_20220320_183212](https://user-images.githubusercontent.com/46828271/159177277-056bf6c1-3918-4ef0-9ce2-9324e04f36a0.png)

**Comment by MilkyDeveloper** [comment]
The upstream kernel doesn't uses `binderfs` instead of `binder`. The ChromeOS kernel doesn't support DKMS, and I am not willing to maintain a niche `binder` implementation from Anbox directly into the kernel. If you would have Googled around, you would have seen the fact that `/dev/binder` isn't created with the upstream kernel, and you need to run:
```
mkdir /dev/binder
mount -t binder binder /dev/binder
```
