### ISSUE TITLE
Working on ARM architectures

### ISSUE THREAD

**Issue by EMLommers** [cb-linux/breath#120]
Is ARMv7 / ARMv8 supported?
like Chromebook ACER R13 (OAK / ELM) with MT8173 and PowerVR 625

**Comment by MilkyDeveloper** [comment]
No. As it says on the docs, x64 is much easier to work with than ARM regarding the boot process and USB layout. Given that even Cadmium doesn't support the MT8173, I won't be adding ARM support.

**Comment by timmypidashev** [comment]
I recommend taking a look at the [supported devices list](https://cb-linux.github.io/breath/docs.html#/?id=is-your-chromebook-not-on-the-list) in the documentation. Generally speaking though, all chromebooks released after 2017 are supported, but I would still try and give the installation a try, since if it doesn't work, then no harm done just reboot out of dev mode. Here's something interesting I found when searching for your chromebook in particular as well(https://archlinuxarm.org/platforms/armv8/mediatek/acer-chromebook-r13). Hope it helps :)

**Comment by MilkyDeveloper** [comment]
@timmypidashev the device isn't listed there and ARM does not equal x86. There are a million different things between ARM and x86.
