### ISSUE TITLE
HP Chromebook 11 G6 EE

### ISSUE THREAD

**Issue by martindmtrv** [cb-linux/breath#122]
Doesn't audio not working on this Apollo Lake CPU tried for apollo lake audio install and "everything else".

Exact model from bottom of boot screen is is SNAPPYE25-B3B-32Y-K3Z-E3Q-A7B

Anything else I can provide? I'm running Ubuntu XFCE.

Also maybe a bit of a sidetrack but I would love to get this working under EndeavorOS! Just curious is it possible to somehow have these sound drivers available in the AUR?

**Comment by MilkyDeveloper** [comment]
What's the output of `dmesg` and the file in `/tmp` created by `alsa-info`?

**Comment by martindmtrv** [comment]
The dmesg output:
[dmesg.txt](https://github.com/cb-linux/breath/files/8343640/dmesg.txt)

alsa-info output from /tmp:
[alsa-info.txt](https://github.com/cb-linux/breath/files/8343643/alsa-info.txt)

**Comment by MilkyDeveloper** [comment]
Hmm... it appears that the soundcards are present. Does `speaker-test` work?

**Comment by martindmtrv** [comment]
`speaker-test` fails to run for me I get the following output:

[speaker-test.txt](https://github.com/cb-linux/breath/files/8344213/speaker-test.txt)

file is long because it gets stuck in a loop it seems and just spams stdout and stderr with the same messages.

When trying to open the volume mixer panel it just hangs on `Establishing connection to PulseAudio. Please wait...`

**Comment by MilkyDeveloper** [comment]
Try removing PulseAudio by running `sudo apt remove pulseaudio* -y`

**Comment by martindmtrv** [comment]
Removing pulseaudio then rebooting now speaker-test works! 

Audio works in firefox too! Only problem is there is no way to control the volume as the system volume control still hangs in the mixer. The status bar says muted as well; but it seems to play.

Any way to enable volume controls?

**Comment by MilkyDeveloper** [comment]
Yeah, these are known issues that trace back to #113, PulseAudio/Pipewire are incompatible. Headphone jacks also don't work because of this. You can control the volume by setting up [this comment](https://github.com/cb-linux/breath/issues/29#issuecomment-1057830881) or by launching `alsamixer` and controlling the `Master` volume.

**Comment by MilkyDeveloper** [comment]
In installs created with the commit I just published, removing PulseAudio/Pipewire should be done by default.

**Comment by ericwoud** [comment]
Pulseaudio can be configured to control Apollo lake audio. The mixer control names of the driver are not standard, pulseaudio does not find the right controls. If you tell pulseaudio which controls it should use in a custom profile file, it works fine.

**Comment by MilkyDeveloper** [comment]
@ericwoud I see. Are mixer control names each volume bar in `alsamixer`? Could I fix this on the kernel level?

**Comment by MilkyDeveloper** [comment]
Also, couldn't PulseAudio just use a UCM with `module-alsa-card`?

**Comment by ericwoud** [comment]
I think the names are fixed in the driver 

I did not succeed in ucm, did not find how to link the volume control to the mixer....

It is possible to make a udev rule for the APL soundcard, that will make pulseaudio to apply the profile from a custom file, only for this card, if present 

I'll paste my profile and path files here again, since it was considered off topic in the sof issue.

This is what I did in pulseaudio:

Note I have overwritten (after backup) /usr/share/pulseaudio/alsa-mixer/profile-sets/default.conf . I did this for a quick test. I should use a different file name and a udev rule to make the profile-set file load only on the specific card. This makes other hardware using the original default.conf.

```
$ cat /usr/share/pulseaudio/alsa-mixer/profile-sets/default.conf 

# This file is a custom file intended for PulseAudio.

; Sound Open Firmware - Apollo Lake Chromebook

[General]
auto-profiles = no

[Mapping analog-stereo-speaker]
description = Speaker
device-strings = hw:%f,0
channel-map = left,right
direction = output
priority = 9
paths-output = sof-apl-speaker-output

[Profile myprofile]
description = My description
output-mappings = analog-stereo-speaker
priority = 60
```
And:
```	
$ cat /usr/share/pulseaudio/alsa-mixer/paths/sof-apl-speaker-output.conf 

# This file is a custom file intended for PulseAudio.

; Sound Open Firmware - Apollo Lake DA7219 Speaker Path
;
; Works with:
; sof-bxtda7219max

[General]
priority = 200
description-key = analog-output-speaker

[Properties]
device.icon_name = audio-speakers

[Element PGA1.0 1 Master]
volume = merge
override-map.1 = all
override-map.2 = all-left,all-right

[Element Spk]
switch = mute
```
So I did not use an ucm file at all. It is only an extra step in the process. Things get lost in the extra translation or are simply not possible. I can make better customisation writing a pulseaudio profile and path directly.

Now I use 'sudo alsamixer' and see how the gnome volume control changes the volume `PGA1.0 1 Master` in the alsa-mixer and that `Spk` gets switched when activating mute in gnome-settings. `sudo alsactl monitor` also shows events on the mixer.

Anyway, this is only the first step.

It would be nice to get some sound from the headset somehow...

**Comment by ericwoud** [comment]
Now I see  in this file https://github.com/thesofproject/alsa-ucm-conf/blob/master/ucm2/hda-dsp/HiFi.conf

The following that looks like something we would need... Guess ucm2 is also possible.... Make a ucm with the control names from my previous post 

```
SectionDevice."Speaker" {
	Comment "Speaker"

	ConflictingDevice [
		"Headphones"
	]

	EnableSequence [
		cset "name='Headphone Playback Switch' 0,0"
		cset "name='Speaker Playback Switch' 1,1"
	]

	Value {
		PlaybackPriority 100
		PlaybackPCM "hw:${CardId},7"
		PlaybackMixerElem "Speaker"
		PlaybackMasterElem "Master"
		PlaybackVolume "Speaker Playback Volume"
		PlaybackSwitch "Speaker Playback Switch"
	}
}

```

**Comment by MilkyDeveloper** [comment]
@ericwoud I would reccomend you to quit this. Fuck audio on any chromebooks. I ended up frying my speaker :D. PulseAudio is so fucked up that it can fry my speakers while ALSA cannot.

**Comment by ericwoud** [comment]
So you are not interested in composing an ucm file? Before it looked like you are ..

**Comment by MilkyDeveloper** [comment]
No? Audio already works with pure ALSA. PulseAudio is stupidity on chromebooks.

**Comment by MilkyDeveloper** [comment]
I never got volume working, but softvol+dmix worked great to emulate PulseAudio. I have a huge dump of chromebook UCM files from the ChromeOS overlays, [located here](https://github.com/cb-linux/cb-ucm). `Snappy`/`Reef` oddly don't have UCM files in their overlay, but I think you have a `bxtda7219max` card. In that case, you could probably look [here](https://github.com/cb-linux/cb-ucm/tree/main/coral/common) for UCM files of the sister baseboard of `reef`, `coral`.

Do note that ChromeOS doesn't use SOF for these devices, so these UCM files probably won't work.

You can use [this search filter](https://github.com/search?q=sof+repo%3Acb-linux%2Fcb-ucm+filename%3A*sof*&type=Code&ref=advsearch&l=&l=) over my repo to find all UCMs that are made for SOF.
