### ISSUE TITLE
Update the instructions to indicate how large a USB is required

### ISSUE THREAD

**Issue by RodBarnes** [cb-linux/breath#69]
It is a long process -- understandably so -- to build the USB and it is frustrating only to get near the end and find the USB wasn't large enough and have to do it all over again. :--)  I expected a 4GB would be sufficient since that holds standard Ubuntu ISOs but it wasn't large enough for this.

I realize the requirements will e different for the CLI vs GUI versions for install.

**Comment by MilkyDeveloper** [comment]
I understand thinking that 4GB would be sufficient, but the USB size needs to be 8GB as a minimum since the Ubuntu ISO is compressed. Flashing the ISO to a USB would still leave it compressed, but it's a very stripped down version of Ubuntu compared to the full-fledged version Breath runs.

Thanks for the feedback ;D

**Comment by RodBarnes** [comment]
Thanks for explaining.  I started the next run with a 32GB.  I figured that would be adequate. ;-)
